print("welcome to my claculator")
print("you dont need to put in any + or - or / or *")
print("+")
firstnumber =int(input("Enter first number"))
secondnumber =int(input("Enter second number"))
output =(firstnumber+secondnumber)
print(output)
subratractionnumber1 =int(input("Enter subtraction number"))
subratractionnumber2 =int(input("Enter second subtraction number"))
subractionoutput=(subratractionnumber1-subratractionnumber2)
print(subractionoutput)
print("enter multipluying number")
multiplyuingnumber1 =int(input("Enter first multipluying number"))
multiplyuingnumber2 =int(input("Enter second multipluying number"))
multipluyingoutput =(multiplyuingnumber1*multiplyuingnumber2)
print(multipluyingoutput)
print("Enter division number")
divisionnumber1 =int(input("Enter first division number"))
divisionnumber2 =int(input("Enter second divison number"))
divisionoutput =(divisionnumber1/divisionnumber2)
if divisionnumber1 == 0:
    print("Error divison by zero 0")
if divisionnumber2 == 0:
    print("Error division by zero")